version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  sales-bot:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - WEBHOOK_URL=${WEBHOOK_URL:-}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL:-}
      - DASHBOARD_URL=${DASHBOARD_URL:-http://localhost:3000}
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data: