name: Deploy Redis-Enhanced Bot

on:
  push:
    branches: [main]
    paths:
      - 'agent/logic_redis.py'
      - 'api/main_redis.py'
      - 'requirements_redis.txt'
      - 'Dockerfile.redis'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Redis version
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.redis
        push: true
        tags: |
          ghcr.io/instabidsai/sales-bot-redis:latest
          ghcr.io/instabidsai/sales-bot-redis:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max